### PR TITLE
Add -S: scale bars relative to max physical size

### PR DESCRIPTION
**Pull request by qneill**
Hi!
I thought it would be nice to visualize the size of the used/free space relative to the physical size of the disks, so I added a '-S' option, see comment.

### CODE REVIEW

**Comment by qneill** [comment]
Trying to get the comment to display correctly..., not having much luck, "preformatted" not working.

 I finally just split the output where the bars started:

**before**
`$ pydf`
`Filesystem Size  Used Avail Use% \` 
`                                                                      Mounted on`
`/dev/sdb1   15G 9458M 4654M 63.5 \`
`[###########################################........................] /`
`/dev/sdb6  200G   37G  152G 18.6 \`
`[############.......................................................] /home`
`/dev/sda2  849G  697G  109G 82.1 \`
`[#######################################################............] /v`
`/dev/sda1  984G  300G  634G 30.5 \`
`[####################...............................................] /z`

**after (note leading/trailing whitespace isn't shown correctly)**

`$ pydf -S`
`Filesystem Size  Used Avail Use% \`
`                                                                      Mounted on`
`/dev/sdb1   15G 9458M 4654M 63.5 \`
`[~]                                                                   /`
`/dev/sdb6  200G   37G  152G 18.6 \`
`[##..........]                                                        /home`
`/dev/sda2  849G  697G  109G 82.1 \`
`[###############################################..........]           /v`
`/dev/sda1  984G  300G  634G 30.5 \`
`[####################...............................................] /z`

**Comment by k4rtik** [comment]
Hi, @qneill I am not the maintainer of pydf, I am just maintaining the PyPI package. See https://github.com/k4rtik/pydf#pypi-package-for-pydf

**Comment by qneill** [comment]
Thanks @k4rtik  I see that now, will try a pull request to https://github.com/garabik/pydf

**Comment by k4rtik** [comment]
Cool! I wasn't aware @garabik is now on GitHub. Thanks for sharing the link, I will link to that repo in the README.

**Pull request closed without merging**
